export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  INVALID_DIMENSION_COMBINATION = 'INVALID_DIMENSION_COMBINATION',
  HCM_UNAVAILABLE = 'HCM_UNAVAILABLE',
  SYNC_CONFLICT = 'SYNC_CONFLICT',
  IDEMPOTENCY_VIOLATION = 'IDEMPOTENCY_VIOLATION',
  NOT_FOUND = 'NOT_FOUND',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
}
